# Here you can set the exit key from the program.
exit_key: q

# Here you can set title and text for main screen
title_main_screen: MAIN MENU
text_main_screen: example text

# Here you must specify path to catalog with scripts.
# All scripts must be executable.
path_to_scripts: ./scripts/

# Here you can edit menu items and submenu items.
menu_items:
- name: 'Test SSH Connection (check ssh to hosts)'
  script: 'echo'
  text: 'sample text'
  checkbox: y
  items:
  - name: 0.0.0.0
    script:
    text: 'default host'
    items:

  - name: 127.0.0.0
    script:
    text: 'localhost'
    items:

- name: Backup (backup all devices in /tmp/)
  script:
  text: 'sample text 2'
  items:
  - name: 0.0.0.0
    script:
    text: 'default host'
    items:

  - name: 127.0.0.0
    script:
    text: 'localhost'
    items:

- name: Startup Provisioning
  script: 'example.py'
  text: "You are about to run startup provisioning tool."
  items:

- name: Update Provisioning
  script:
  text: "You are about to run update provisioning tool."
  items:

- name: Troubleshooting
  script:
  text:
  items:

- name: Verifications
  script:
  text:
  items:

- name: Host Files
  script:
  text:
  items:

- name: Read Me
  script:
  text:
  items:

- name: Login Device
  script:
  text:
  items:

- name: Exit
  script:
  text:
  items:

- name: License
  script:
  text:
  items:

